[build]
  command = "yarn install && yarn build"
  publish = "build"
  base = "packages/app"


[[redirects]]
  from = "/"
  to = "/restricted"
  status = 301
  force = true
  conditions = {Country = ["US"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200



